config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'welcomes#index'

  authenticate :user do
    resources :profiles, only: [:index, :show]
    resources :watchedshows, only: [:create]
    resources :friendships
  end

  resources :conversations do
    resources :messages
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @list_of_watchedtvshows = Watchedshow.where(user: current_user)
    @show = Tvshow.new
    @rating = Watchedshow::RATING
    @add_watched_show = Watchedshow.new
    gon.tvshows = Tvshow.pluck(:name)
    gon.posters = Tvshow.all.map{|show| show.posterlink}
  end

  def show
    @user = User.find(params[:id])
    @next_user = (User.all - [current_user]).sample
    @list_of_watchedtvshows = Watchedshow.where(user: @user)
  end

end

app/views/profiles/_stars.html.erb
<% locals[:gold].to_i.times do %>
  <svg height="25" width="20" class="star rating" data-rating="1">
    <polygon fill="#ffbf00" points="10,0 13.09,6.583 20,7.639 15,12.764 16.18,20 10,16.583 3.82,20 5,12.764 0,7.639 6.91,6.583 "/>
  </svg>
<% end %>
<% locals[:silver].to_i.times do %>
  <svg height="25" width="20" class="star rating" data-rating="1">
    <polygon fill="#DDDDDD" points="10,0 13.09,6.583 20,7.639 15,12.764 16.18,20 10,16.583 3.82,20 5,12.764 0,7.639 6.91,6.583 "/>
  </svg>
<% end %>

app/views/profiles/index.html.haml
.row
  .small-4.columns#card_padding
    .card
      %img{ src: "#{current_user.avatar.large_avatar}"}
      .content
        %p#default_font= current_user.username
  .small-4.columns#card_padding.small-push-3.end
    .card
      %p#default_font Add a new show that you've watched!
      =render template: "watchedshows/new.html.haml"

.row
  .small-12.columns
    %ul.small-block-grid-5#poster_image
      - @list_of_watchedtvshows.each do |show|
        %li
          %img{src: "#{show.tvshow.posterlink}"}
          %h4#default_font= link_to show.tvshow.name, show.tvshow.imdblink
          %span= render 'profiles/stars', locals: {gold: show.rating, silver: 5 - show.rating}

app/views/profiles/show.html.haml
.row
  .small-5.columns.small-centered#card_padding
    .card
      %img{ src: "#{@user.avatar.medium_avatar}"}
      .content
        %p#default_font= @user.username
        .row
          .small-6.columns
            = link_to "Chillin?", friendships_path(match_id: @user), method: :post, class: "button success small"
          .small-6.columns
            = link_to "Another time", profile_path(id: @next_user), class: "button alert small"

.row
  .small-12.columns
    %ul.small-block-grid-5#poster_image
      - @list_of_watchedtvshows.each do |show|
        %li
          %img{src: "#{show.tvshow.posterlink}"}
          %h4#default_font= link_to show.tvshow.name, show.tvshow.imdblink
          %span= render 'profiles/stars', locals: {gold: show.rating, silver: 5 - show.rating}