config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'welcomes#index'

  authenticate :user do
    resources :profiles, only: [:index, :show]
    resources :watchedshows, only: [:create]
    resources :friendships
  end

  resources :conversations do
    resources :messages
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :match, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @next_user = (User.all - [current_user]).sample
    @all_people = User.where.not("id = ?",current_user.id).order("created_at DESC")
  end

  def create
    @friendship = current_user.friendships.build(match_id: params[:match_id], approved: "false")
    if @friendship.save
      flash[:notice] = "Good vibes sent!"
      redirect_to root_path
    else
      flash[:error] = "Unable to send request :("
      redirect_to root_path
    end
  end

  def update
    @friendship = Friendship.where(match_id: current_user, user_id: params[:id]).first
    @friendship.update(approved: true)
    if @friendship.save
      flash[:notice] = 'You two are now connected!'
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong :( try again, please!'
      redirect_to root_path
    end
  end

  def destroy
    @friendship = Friendship.where(match_id: [current_user, params[:id]]).where(user_id: [current_user, params[:id]]).last
    @friendship.destroy
    flash[:notice] = "Removed friendship"
    redirect_to root_path
  end

end

app/views/friendships/index.html.haml
.row#card_padding
  .small-10.columns.small-centered
    =link_to "Find others to chill with!", profile_path(id: @next_user), class: "signupheader"
.row
  .small-10.small-centered
  %p.defaultfont People who have checked out this app:
  %ul.small-block-grid-3
    - @all_people.each_with_index do |user, index|
      %li
        .image-wrapper.overlay-fade-in
          %img{src: "#{user.avatar.large_avatar}"}
          .image-overlay-content
          %h2="#{user.username}"
          = link_to 'Profile', profile_path(user), class: "button tiny profile_button"
          = link_to "Send good vibes!", "#", class: "button success tiny start-conversation conversation_button", "data-sid" => current_user.id, "data-rip" => user.id
-if !current_user.requested_matches.empty?
  .row#card_padding
    .small-10.columns.small-centered
      %p.signupheader Chill requests!
      %ul.small-block-grid-3
        - current_user.requested_matches.each do |request|
          %li
            .image-wrapper.overlay-fade-in
              %img{src: "#{request.avatar.small_avatar}"}
              .image-overlay-content
                %h2= "#{request.username}"
                = link_to "Accept", friendship_path(id: request), method: "put", class: "button success tiny"
                = link_to "Decline", friendship_path(id: request), method: :delete, class: "button tiny alert"

-if !current_user.matches.empty?
  .row#card_padding
    .small-10.columns.small-centered
      %p.signupheader Who's down to chill?
      %ul.small-block-grid-3
        - current_user.matches.each do |user|
          %li
            .image-wrapper.overlay-fade-in
              %img{src: "#{user.avatar.large_avatar}"}
              .image-overlay-content
                %h2= "#{user.username}"
                = link_to 'Profile', profile_path(user), class: "button tiny profile_button"
                = link_to "Send good vibes!", "#", class: "button success tiny start-conversation conversation_button", "data-sid" => current_user.id, "data-rip" => user.id
-else
  .row
    .small-10.small-centered
      %p.signupheader Nobody to chill with yet :(